import PyInstaller.__main__
import os

PyInstaller.__main__.run([
    'main.py',
    '--name=JARVIS',
    '--onefile',
    '--windowed',
    '--noconfirm',
    '--clean',
    '--exclude-module=torch',
    '--exclude-module=torchvision',
    '--exclude-module=transformers',
    '--exclude-module=tensorflow',
    '--exclude-module=keras',
    '--exclude-module=nltk',
    '--exclude-module=spacy',
    '--exclude-module=PyAudio',
    '--hidden-import=customtkinter',
    '--hidden-import=speech_recognition',
    '--hidden-import=edge_tts',
    '--hidden-import=pyttsx3',
    '--hidden-import=psutil',
    '--hidden-import=pyautogui',
    '--hidden-import=elevenlabs',
    '--hidden-import=groq',
    '--hidden-import=sounddevice',
    '--hidden-import=soundfile',
    '--hidden-import=numpy',
    '--hidden-import=requests',
    '--hidden-import=comtypes',
    '--hidden-import=dotenv',
    '--collect-data=customtkinter',
])
